Repository sanger-tol/blobtoolkit, pull requests merged in 2023-05, with the labels that each got.

#63 View2
  conf/modules.config
  modules/local/blobtoolkit/images.nf
  subworkflows/local/view.nf
  workflows/blobtoolkit.nf
Labels: enhancement, help wanted

#68 busco_sequences directory - no tar.gz !
  modules/local/blobtoolkit/extractbuscos.nf
  modules/local/targz.nf
  subworkflows/local/busco_diamond_blastp.nf
Labels: enhancement

#71 update images
  modules/local/blobtoolkit/images.nf
  subworkflows/local/view.nf
Labels: enhancement

#72 Merging main into dev
  README.md
  lib/WorkflowMain.groovy
  nextflow.config
Labels: documentation, enhancement

#73 setting for v0.2.0
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
  nextflow.config
Labels: documentation, enhancement
