Repository sanger-tol/blobtoolkit, pull requests merged in 2023-03, with the labels that each got.

#44 BLOBTOOLS subworkflow: GENERATE_CONFIG module
  README.md
  conf/modules.config
  conf/test.config
  docs/output.md
  docs/parameters.md
  modules/local/add_summary_to_metadata.nf
  modules/local/generate_config.nf
  subworkflows/local/blobtools.nf
  subworkflows/local/input_check.nf
  workflows/blobtoolkit.nf
Labels: enhancement

#52 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug

#56 decision records
  docs/decision-records/README.md
Labels: documentation
